version: 2
updates:
  # Python dependencies configuration
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"  # Häufigere Überprüfungen für Sicherheitsupdates
      time: "06:00"
      timezone: "Europe/Berlin"
    # Allow all dependency types for security updates
    allow:
      - dependency-type: "all"  # Erlaubt Sicherheitsupdates für alle Abhängigkeitstypen
    # Ignore major version updates by default
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
      - "security"
    commit-message:
      prefix: "🔒 SECURITY"
      prefix-development: "🔒 SECURITY (dev)"
      include: "scope"
    # Specific configurations for security-critical packages
    groups:
      security-updates:
        patterns:
          - "cryptography"
          - "aiohttp"
          - "tqdm"
          - "telethon"
          - "python-dotenv"
          - "pydub"
          - "peewee"
        update-types:
          - "patch"
          - "minor"
        # Automatisches Merging erfolgt über GitHub Actions Workflows

  # GitHub Actions Updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
      - "security"
    commit-message:
      prefix: "🔄 GITHUB-ACTIONS"
      include: "scope"
    # Ignore major version updates by default
    ignore:
      - dependency-name: "actions/*"
        update-types: ["version-update:semver-major"]

  # Docker Images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "docker"
      - "security"
    commit-message:
      prefix: "🐳 DOCKER"
      include: "scope"
    # Ignore major version updates by default
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]