# Diese Datei unterstützt verschiedene Finanzierungsmodelle für das Projekt
# Dokumentation: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [Elpablo777]  # GitHub Sponsors
custom: 
  - "https://www.paypal.me/elpablo777"  # PayPal
  # Weitere benutzerdefinierte Links können hier hinzugefügt werden

# Weitere unterstützte Finanzierungsplattformen
# Entfernen Sie die Kommentarzeichen und ersetzen Sie die Platzhalter bei Bedarf
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: platform-name/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username