# RepoSovereign Prime Configuration
# ===================================
# Konfiguration f체r die autonome GitHub Repository Governance Engine

governance:
  # Zero Defect Tolerance Konfiguration
  zero_defect_tolerance: true
  max_issue_age_hours: 24
  critical_issue_response_minutes: 15
  
  # Predictive Maintenance
  predictive_maintenance: true
  pattern_analysis_depth: 30  # Tage f체r historische Analyse
  maintenance_prediction_confidence: 0.75
  
  # Autonomous Resolution
  autonomous_resolution: true
  auto_resolution_confidence_threshold: 0.8
  max_complexity_for_auto_resolution: 7  # 1-10 Skala
  
  # Security-First Architecture
  security_first: true
  threat_hunting_interval_minutes: 30
  security_response_time_minutes: 5

thresholds:
  # Issue-Management
  max_issue_age_hours: 24
  auto_resolution_confidence: 0.8
  complexity_threshold: 7
  
  # Security
  security_response_minutes: 5
  vulnerability_tolerance: "none"  # none, low, medium
  
  # Quality Gates
  min_code_coverage: 0.80
  min_test_pass_rate: 0.95
  min_security_score: 0.90
  min_dependency_health: 0.85
  min_documentation_completeness: 0.75
  
  # Performance
  max_build_time_minutes: 10
  max_test_time_minutes: 5

ai_models:
  # Dynamische Modell-Auswahl basierend auf Komplexit채t
  simple_tasks: "gpt-3.5-turbo"      # Triage, einfache Antworten
  medium_tasks: "gpt-4-turbo"        # Code-Review, Dokumentation
  complex_tasks: "gpt-4"             # Refactoring, Architektur
  code_analysis: "codex"             # Code-Generierung, Bug-Fixes
  security_analysis: "gpt-4"         # Sicherheitsanalyse

automation:
  # Issue Resolution
  auto_close_stale_issues: true
  stale_issue_days: 30
  auto_label_issues: true
  auto_assign_issues: true
  
  # Pull Request Management
  auto_merge_enabled: true
  auto_merge_conditions:
    - "all_checks_passed"
    - "required_reviews_approved" 
    - "no_conflicts"
    - "security_scan_passed"
  
  # Dependency Management
  auto_update_dependencies: true
  security_updates_immediate: true
  minor_updates_weekly: true
  major_updates_manual: true
  
  # Documentation
  auto_generate_api_docs: true
  auto_update_changelog: true
  auto_update_readme: true

security:
  # Continuous Monitoring
  enable_codeql: true
  enable_dependency_scanning: true
  enable_secret_scanning: true
  enable_vulnerability_alerts: true
  
  # Response Actions
  auto_patch_critical_vulnerabilities: true
  auto_rollback_compromised_dependencies: true
  immediate_notification_on_secrets: true
  
  # Compliance
  require_signed_commits: false
  require_branch_protection: true
  require_pr_reviews: true
  require_status_checks: true

quality:
  # Code Quality
  enforce_coding_standards: true
  auto_format_code: true
  auto_fix_lint_issues: true
  
  # Testing
  require_tests_for_new_code: true
  auto_run_tests_on_pr: true
  require_coverage_maintenance: true
  
  # Performance
  monitor_performance_regression: true
  auto_optimize_slow_queries: false  # Zu riskant f체r Auto-Fix

notifications:
  # Channels
  slack_webhook: ""
  email_recipients: []
  github_notifications: true
  
  # Notification Rules
  notify_on_critical_issues: true
  notify_on_security_alerts: true
  notify_on_failed_auto_resolution: true
  notify_on_quality_degradation: true
  
  # Notification Frequency
  immediate_for_critical: true
  daily_summary: true
  weekly_report: true

reporting:
  # Report Generation
  generate_governance_reports: true
  report_retention_days: 90
  
  # Metrics Collection
  collect_quality_metrics: true
  collect_security_metrics: true
  collect_performance_metrics: true
  
  # Export Formats
  export_json: true
  export_csv: true
  export_dashboard: true

integration:
  # GitHub Integration
  github_api_token_env: "GITHUB_TOKEN"
  github_app_installation_id: ""
  
  # External Tools
  sonarqube_url: ""
  snyk_token_env: "SNYK_TOKEN"
  
  # Monitoring Tools
  datadog_api_key_env: "DATADOG_API_KEY"
  newrelic_api_key_env: "NEWRELIC_API_KEY"

branches:
  # Branch Protection
  protected_branches:
    - "main"
    - "develop"
  
  # Auto-Merge Branches
  auto_merge_branches:
    - "copilot/*"
    - "dependabot/*"
    - "renovate/*"
  
  # Branch Naming Conventions
  enforce_branch_naming: true
  branch_patterns:
    feature: "feature/*"
    bugfix: "bugfix/*"
    hotfix: "hotfix/*"
    release: "release/*"

versioning:
  # Semantic Versioning
  auto_semantic_versioning: true
  version_bump_rules:
    breaking_change: "major"
    new_feature: "minor"
    bug_fix: "patch"
    dependency_update: "patch"
  
  # Release Management
  auto_create_releases: true
  auto_generate_release_notes: true
  auto_tag_releases: true

experimental:
  # Experimentelle Features (mit Vorsicht nutzen)
  ai_code_generation: false
  auto_refactoring: false
  predictive_bug_detection: true
  intelligent_test_generation: false