# Beispiel-Konfiguration mit Proxy-Einstellungen
telegram:
  api_id: "YOUR_API_ID"
  api_hash: "YOUR_API_HASH"
  phone_number: "+491234567890"

proxy:
  type: socks5  # oder http
  host: proxy.example.com
  port: 1080
  username: your_username  # Optional
  password: your_password   # Optional

download:
  download_dir: downloads
  max_concurrent_downloads: 3
  max_file_size: 100000000
  allowed_extensions: .mp3,.m4a,.flac,.ogg,.wav
  max_retries: 3
  retry_delay: 5
  checksum_algorithm: sha256

performance:
  chunk_size: 8192
  timeout: 30
  connection_pool_size: 10