name: PR Review and Security Check

# Minimal required permissions for the workflow
permissions:
  contents: read  # For checking out code
  packages: read  # For downloading dependencies
  actions: read   # For reading workflow data
  security-events: write  # For security scanning
  checks: write   # For creating check runs
  pull-requests: write  # For PR comments
  issues: write   # For creating issues

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  pr-review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run PR Cleanup Script
      run: |
        python scripts/pr_cleanup.py
    
    - name: Upload PR Review Report
      uses: actions/upload-artifact@v4
      with:
        name: pr-review-report
        path: pr_review_report.json

  security-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety
    
    - name: Run Security Fix Script
      run: |
        if [ -f "scripts/security_fix.py" ]; then
          python scripts/security_fix.py
        else
          echo "Error: scripts/security_fix.py not found. Failing workflow."
          exit 1
        fi
    
    - name: Run Safety Check
      run: |
        python check_security.py
    
    - name: Check for security issues
      run: |
        # Wenn das Sicherheitsprüfungs-Skript Probleme findet, wird es einen Exit-Code != 0 zurückgeben
        echo "Security check completed"